#!/bin/bash
BASEDIR=$(dirname $(readlink -f ${0}))
BASENAME=$(basename ${0})

if [[ -z "${JAVA_HOME}" ]]
then
  echo "Please set JAVA_HOME environment variable"
  exit 1
fi

${JAVA_HOME}/bin/java -jar ${BASEDIR}/lib/FinCal.jar "$@"
